import 'package:cloud_firestore/cloud_firestore.dart';

class SeedSummary {
  const SeedSummary({
    required this.collectionCount,
    required this.documentCount,
  });

  final int collectionCount;
  final int documentCount;
}

class SeedService {
  SeedService({FirebaseFirestore? firestore})
    : _firestore = firestore ?? FirebaseFirestore.instance;

  final FirebaseFirestore _firestore;

  Future<SeedSummary> seedDemoData() async {
    await _resetCoCurriculumCollections();

    final collections = _seedCollections();
    final batch = _firestore.batch();
    var documentCount = 0;

    collections.forEach((collectionName, documents) {
      for (final document in documents) {
        final id = (document['id'] ?? document['uid'] ?? '').toString();
        if (id.isEmpty) continue;

        final ref = _firestore.collection(collectionName).doc(id);
        batch.set(ref, document, SetOptions(merge: true));
        documentCount += 1;
      }
    });

    await batch.commit();
    return SeedSummary(
      collectionCount: collections.length,
      documentCount: documentCount,
    );
  }

  Future<void> _resetCoCurriculumCollections() async {
    const collections = [
      'activities',
      'activity_registrations',
      'credit_claims',
      'attendance_records',
    ];

    for (final collectionName in collections) {
      final snapshot = await _firestore.collection(collectionName).get();
      if (snapshot.docs.isEmpty) {
        continue;
      }

      final batch = _firestore.batch();
      for (final doc in snapshot.docs) {
        batch.delete(doc.reference);
      }
      await batch.commit();
    }
  }

  Map<String, List<Map<String, dynamic>>> _seedCollections() {
    const semester = 'Semester 2, 2025/2026';
    const createdAt = '2026-04-01T08:00:00.000Z';

    // ── users ────────────────────────────────────────────────────────────────
    final users = [
      {
        'uid': 'stu-001',
        'fullName': 'Ahmad Malik',
        'email': 'student@demo.sa',
        'role': 'student',
        'matricId': '2023012345',
        'staffId': '',
        'faculty': 'Faculty of Computing',
        'programme': 'Bachelor of Computer Science',
        'semester': semester,
        'currentSemester': semester,
        'accountStatus': 'Active',
        'maxCreditHours': 9,
        'completedSubjects': ['CSC1101', 'CSC1201'],
        'themeRole': 'student',
        'avatarInitials': 'AM',
        'createdAt': createdAt,
      },
      {
        'uid': 'stu-002',
        'fullName': 'Siti Aisyah',
        'email': 'student2@demo.sa',
        'role': 'student',
        'matricId': '2023012346',
        'staffId': '',
        'faculty': 'Faculty of Computing',
        'programme': 'Bachelor of Computer Science',
        'semester': semester,
        'currentSemester': semester,
        'accountStatus': 'Active',
        'maxCreditHours': 9,
        'completedSubjects': ['CSC1101'],
        'themeRole': 'student',
        'avatarInitials': 'SA',
        'createdAt': createdAt,
      },
      {
        'uid': 'stu-003',
        'fullName': 'Haziq Ibrahim',
        'email': 'student3@demo.sa',
        'role': 'student',
        'matricId': '2023012350',
        'staffId': '',
        'faculty': 'Faculty of Computing',
        'programme': 'Bachelor of Information Technology',
        'semester': semester,
        'currentSemester': semester,
        'accountStatus': 'Active',
        'maxCreditHours': 9,
        'completedSubjects': ['CSC1101', 'CSC1201', 'CSC1301'],
        'themeRole': 'student',
        'avatarInitials': 'HI',
        'createdAt': createdAt,
      },
      {
        'uid': 'lec-001',
        'fullName': 'Dr. Nur Hidayah',
        'email': 'lecturer@demo.sa',
        'role': 'lecturer',
        'matricId': '',
        'staffId': 'L20018',
        'faculty': 'Faculty of Computing',
        'programme': 'Academic Staff',
        'semester': semester,
        'currentSemester': semester,
        'accountStatus': 'Active',
        'maxCreditHours': 0,
        'completedSubjects': <String>[],
        'themeRole': 'lecturer',
        'avatarInitials': 'NH',
        'createdAt': createdAt,
      },
      {
        'uid': 'lec-002',
        'fullName': 'Dr. Nabilah Hassan',
        'email': 'lecturer2@demo.sa',
        'role': 'lecturer',
        'matricId': '',
        'staffId': 'L20102',
        'faculty': 'Student Affairs',
        'programme': 'Academic Staff',
        'semester': semester,
        'currentSemester': semester,
        'accountStatus': 'Active',
        'maxCreditHours': 0,
        'completedSubjects': <String>[],
        'themeRole': 'lecturer',
        'avatarInitials': 'NH',
        'createdAt': createdAt,
      },
      {
        'uid': 'lec-003',
        'fullName': 'Encik Danial Rizal',
        'email': 'lecturer3@demo.sa',
        'role': 'lecturer',
        'matricId': '',
        'staffId': 'L20156',
        'faculty': 'Student Affairs',
        'programme': 'Academic Staff',
        'semester': semester,
        'currentSemester': semester,
        'accountStatus': 'Active',
        'maxCreditHours': 0,
        'completedSubjects': <String>[],
        'themeRole': 'lecturer',
        'avatarInitials': 'DR',
        'createdAt': createdAt,
      },
      {
        'uid': 'reg-001',
        'fullName': 'Pn. Siti Nabila',
        'email': 'registrar@demo.sa',
        'role': 'faculty_registrar',
        'matricId': '',
        'staffId': 'R10042',
        'faculty': 'Faculty of Computing',
        'programme': 'Registrar Office',
        'semester': semester,
        'currentSemester': semester,
        'accountStatus': 'Active',
        'maxCreditHours': 0,
        'completedSubjects': <String>[],
        'themeRole': 'faculty_registrar',
        'avatarInitials': 'SN',
        'createdAt': createdAt,
      },
      {
        'uid': 'pad-001',
        'fullName': 'Encik Farhan Adib',
        'email': 'pusatadab@demo.sa',
        'role': 'pusat_adab',
        'matricId': '',
        'staffId': 'PA3409',
        'faculty': 'Student Affairs',
        'programme': 'Pusat Adab',
        'semester': semester,
        'currentSemester': semester,
        'accountStatus': 'Active',
        'maxCreditHours': 0,
        'completedSubjects': <String>[],
        'themeRole': 'pusat_adab',
        'avatarInitials': 'FA',
        'createdAt': createdAt,
      },
      {
        'uid': 'tre-001',
        'fullName': 'Nor Azizah',
        'email': 'treasury@demo.sa',
        'role': 'treasury',
        'matricId': '',
        'staffId': 'T10001',
        'faculty': 'Treasury Department',
        'programme': 'Treasury Services',
        'semester': semester,
        'currentSemester': semester,
        'accountStatus': 'Active',
        'maxCreditHours': 0,
        'completedSubjects': <String>[],
        'themeRole': 'treasury',
        'avatarInitials': 'NA',
        'createdAt': createdAt,
      },
      {
        'uid': 'adm-001',
        'fullName': 'System Administrator',
        'email': 'admin@demo.sa',
        'role': 'admin',
        'matricId': '',
        'staffId': 'ADM9001',
        'faculty': 'ICT Department',
        'programme': 'System Administration',
        'semester': semester,
        'currentSemester': semester,
        'accountStatus': 'Active',
        'maxCreditHours': 0,
        'completedSubjects': <String>[],
        'themeRole': 'admin',
        'avatarInitials': 'SA',
        'createdAt': createdAt,
      },
    ].map((user) => {'id': user['email'], ...user}).toList();

    // ── tuition_fees (one doc per student, keyed by uid) ─────────────────────
    final tuitionFees = [
      {
        'id': 'stu-001',              // doc ID = student uid
        'studentId': 'stu-001',
        'studentName': 'Ahmad Malik',
        'matricId': '2023012345',
        'semester': semester,
        'programme': 'Bachelor of Computer Science',
        'programFee': 1200.00,
        'otherFee': 250.00,
        'outstandingAmount': 1450.00,
        'paymentStatus': 'Unpaid',    // Unpaid | Pending | Paid | Verified
        'isBlocked': true,
        'dueDate': '28 Apr 2026',
        'updatedAt': createdAt,
      },
      {
        'id': 'stu-002',
        'studentId': 'stu-002',
        'studentName': 'Siti Aisyah',
        'matricId': '2023012346',
        'semester': semester,
        'programme': 'Bachelor of Computer Science',
        'programFee': 1200.00,
        'otherFee': 200.00,
        'outstandingAmount': 0.00,
        'paymentStatus': 'Paid',
        'isBlocked': false,
        'dueDate': '',
        'updatedAt': createdAt,
      },
      {
        'id': 'stu-003',
        'studentId': 'stu-003',
        'studentName': 'Haziq Ibrahim',
        'matricId': '2023012350',
        'semester': semester,
        'programme': 'Bachelor of Information Technology',
        'programFee': 1100.00,
        'otherFee': 250.00,
        'outstandingAmount': 1350.00,
        'paymentStatus': 'Pending',
        'isBlocked': false,
        'dueDate': '28 Apr 2026',
        'updatedAt': createdAt,
      },
    ];

    // ── payment_transactions ─────────────────────────────────────────────────
    final paymentTransactions = [
      {
        'id': 'txn-001',
        'studentId': 'stu-002',
        'studentName': 'Siti Aisyah',
        'matricId': '2023012346',
        'semester': semester,
        'amount': 1400.00,
        'referenceNo': 'TXN-2026-0401-7823',
        'paymentMethod': 'Online Transfer',
        'bank': 'Maybank',
        'accountOrCard': '123-456-7890',
        'bankRef': 'IB-20260401-XX',
        'status': 'Verified',          // Pending | Verified | Rejected
        'verifiedBy': 'treasury',
        'remarks': '',
        'module': 'tuition',
        'createdAt': '2026-04-01T09:41:00.000Z',
        'updatedAt': '2026-04-01T10:15:00.000Z',
      },
      {
        'id': 'txn-002',
        'studentId': 'stu-003',
        'studentName': 'Haziq Ibrahim',
        'matricId': '2023012350',
        'semester': semester,
        'amount': 1350.00,
        'referenceNo': 'TXN-2026-0402-5102',
        'paymentMethod': 'Credit Card',
        'bank': '',
        'accountOrCard': '4111111111111111',
        'bankRef': 'CC-20260402-YY',
        'status': 'Pending',
        'verifiedBy': '',
        'remarks': '',
        'module': 'tuition',
        'createdAt': '2026-04-02T11:20:00.000Z',
        'updatedAt': '2026-04-02T11:20:00.000Z',
      },
    ];

    // ── notifications ────────────────────────────────────────────────────────
    final notifications = [
      {
        'id': 'notif-adm-001',
        'userId': 'adm-001',
        'title': 'Firestore seed ready',
        'message':
            'Initial demo documents can be written from the Settings page.',
        'type': 'info',
        'module': 'system',
        'isRead': false,
        'createdAt': createdAt,
        'actionLink': '',
      },
      {
        'id': 'notif-stu-001',
        'userId': 'stu-001',
        'title': 'Chess Strategy Clinic claim approved',
        'message':
            'Your approved co-curriculum credit has been recorded successfully.',
        'type': 'success',
        'module': 'module2',
        'isRead': false,
        'createdAt': createdAt,
        'actionLink': 'claim-002',
      },
      {
        'id': 'notif-stu-002',
        'userId': 'stu-001',
        'title': 'Futsal Performance claim pending review',
        'message':
            'Your latest claim is pending review by Pusat Adab.',
        'type': 'info',
        'module': 'module2',
        'isRead': false,
        'createdAt': createdAt,
        'actionLink': 'claim-001',
      },
      {
        'id': 'notif-pad-001',
        'userId': 'pad-001',
        'title': 'New credit claims submitted',
        'message':
            'Two student claims are ready for review in the co-curriculum module.',
        'type': 'info',
        'module': 'module2',
        'isRead': false,
        'createdAt': createdAt,
        'actionLink': '',
      },
      {
        'id': 'notif-lec-001',
        'userId': 'lec-001',
        'title': 'Updated activity roster available',
        'message':
            'Registration changes were recorded for supervised activities.',
        'type': 'info',
        'module': 'module2',
        'isRead': false,
        'createdAt': createdAt,
        'actionLink': '',
      },
      {
        'id': 'notif-stu-002',
        'userId': 'stu-001',
        'title': 'Academic access blocked',
        'message':
            'Your academic access has been restricted by treasury. Please settle your outstanding fee of RM 1,450.00.',
        'type': 'danger',
        'module': 'tuition',
        'isRead': false,
        'createdAt': createdAt,
        'actionLink': '',
      },
      {
        'id': 'notif-stu-003',
        'userId': 'stu-001',
        'title': 'Payment deadline in 3 days',
        'message':
            'Week 5 deadline: 28 Apr 2026. Pay RM 1,450.00 to avoid access block.',
        'type': 'warning',
        'module': 'tuition',
        'isRead': false,
        'createdAt': createdAt,
        'actionLink': '',
      },
      {
        'id': 'notif-stu-004',
        'userId': 'stu-002',
        'title': 'Payment verified',
        'message':
            'Your payment of RM 1,400.00 has been verified by treasury.',
        'type': 'success',
        'module': 'tuition',
        'isRead': false,
        'createdAt': createdAt,
        'actionLink': '',
      },
      {
        'id': 'notif-stu-005',
        'userId': 'stu-002',
        'title': 'Academic access restored',
        'message':
            'Your academic access has been restored. You can now register for classes, exams, and access academic records.',
        'type': 'success',
        'module': 'tuition',
        'isRead': false,
        'createdAt': createdAt,
        'actionLink': '',
      },
    ];

    // ── subjects ─────────────────────────────────────────────────────────────
    final subjects = [
      {
        'id': 'sub-001',
        'subjectCode': 'CSC2201',
        'subjectName': 'Database Systems',
        'creditHour': 3,
        'faculty': 'Faculty of Computing',
        'prerequisites': ['CSC1101'],
      },
      {
        'id': 'sub-002',
        'subjectCode': 'CSC2401',
        'subjectName': 'Web Application Development',
        'creditHour': 3,
        'faculty': 'Faculty of Computing',
        'prerequisites': <String>[],
      },
    ];

    final subjectOfferings = [
      {
        'id': 'off-001',
        'subjectId': 'sub-001',
        'semester': semester,
        'year': 2026,
        'lecturerId': 'lec-001',
        'lecturerName': 'Dr. Nur Hidayah',
        'schedule': 'Tue 09:00 - 11:00',
        'seats': 30,
        'seatsTaken': 24,
        'status': 'active',
      },
      {
        'id': 'off-002',
        'subjectId': 'sub-002',
        'semester': semester,
        'year': 2026,
        'lecturerId': 'lec-001',
        'lecturerName': 'Dr. Nur Hidayah',
        'schedule': 'Thu 10:00 - 12:00',
        'seats': 25,
        'seatsTaken': 18,
        'status': 'active',
      },
    ];

    final registrationPeriods = [
      {
        'id': 'reg-period-001',
        'semester': semester,
        'startDate': '2026-04-01',
        'endDate': '2026-04-30',
        'isOpen': true,
        'updatedBy': 'reg-001',
        'updatedAt': createdAt,
      },
    ];

    final subjectRegistrations = [
      {
        'id': 'subreg-001',
        'studentId': 'stu-001',
        'subjectOfferingId': 'off-001',
        'semester': semester,
        'registeredAt': createdAt,
        'status': 'completed',
      },
    ];

    Map<String, dynamic> buildActivity({
      required String id,
      required String title,
      required String category,
      required String date,
      required String sessionDate,
      required String venue,
      required String supervisorId,
      required String description,
      required int capacity,
      required int availableSlots,
      required String status,
      bool isCompleted = false,
    }) {
      return {
        'id': id,
        'title': title,
        'name': title,
        'category': category,
        'description': description,
        'date': date,
        'session_date': sessionDate,
        'startTime': '8:00 AM',
        'endTime': '5:00 PM',
        'venue': venue,
        'hours': 8,
        'cats': 2,
        'creditValue': 2,
        'capacity': capacity,
        'availableSlots': availableSlots,
        'supervisorLecturerId': supervisorId,
        'status': status,
        'requiresAttendance': true,
        'managedBy': 'pusat_adab',
        'sourceModule': 'manage_co_curriculum',
        'createdBy': 'pad-001',
        'createdAt': createdAt,
        'updatedAt': createdAt,
        'participantsCount': capacity - availableSlots,
        'maxParticipants': capacity,
        'eligibilityRule': 'all_active_students',
        'isCompleted': isCompleted,
      };
    }

    final activities = [
      buildActivity(
        id: 'act-001',
        title: 'Chess',
        category: 'Academic / Skills / Digital',
        date: '10 May 2026',
        sessionDate: '2026-05-10',
        venue: 'Seminar Hall',
        supervisorId: 'lec-002',
        description:
            'Structured strategy session focused on decision making, planning, and discipline.',
        capacity: 30,
        availableSlots: 10,
        status: 'Active',
        isCompleted: true,
      ),
      buildActivity(
        id: 'act-002',
        title: 'Creative Arts',
        category: 'Academic / Skills / Digital',
        date: '25 May 2026',
        sessionDate: '2026-05-25',
        venue: 'Arts Studio',
        supervisorId: 'lec-002',
        description:
            'Creative expression activity for collaborative art, presentation, and appreciation.',
        capacity: 30,
        availableSlots: 18,
        status: 'Draft',
      ),
      buildActivity(
        id: 'act-003',
        title: '3D Design and Printing',
        category: 'Academic / Skills / Digital',
        date: '26 May 2026',
        sessionDate: '2026-05-26',
        venue: 'Innovation Lab',
        supervisorId: 'lec-001',
        description:
            'Hands-on design workflow involving 3D modelling and print preparation.',
        capacity: 24,
        availableSlots: 9,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-004',
        title: 'Edit like a Pro with Canva',
        category: 'Academic / Skills / Digital',
        date: '29 May 2026',
        sessionDate: '2026-05-29',
        venue: 'Digital Studio',
        supervisorId: 'lec-001',
        description:
            'Digital editing activity for poster, social media, and communication design skills.',
        capacity: 35,
        availableSlots: 12,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-005',
        title: 'Digital Citizenship',
        category: 'Academic / Skills / Digital',
        date: '28 May 2026',
        sessionDate: '2026-05-28',
        venue: 'Lecture Room 2',
        supervisorId: 'lec-001',
        description:
            'Activity on safe online engagement, digital ethics, and responsible participation.',
        capacity: 40,
        availableSlots: 21,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-006',
        title: 'Click Wisely',
        category: 'Academic / Skills / Digital',
        date: '30 May 2026',
        sessionDate: '2026-05-30',
        venue: 'Lecture Room 3',
        supervisorId: 'lec-001',
        description:
            'Awareness-based activity on cyber hygiene and informed digital behaviour.',
        capacity: 40,
        availableSlots: 17,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-007',
        title: 'Outstanding Presentation',
        category: 'Academic / Skills / Digital',
        date: '02 Jun 2026',
        sessionDate: '2026-06-02',
        venue: 'Auditorium 1',
        supervisorId: 'lec-002',
        description:
            'Communication activity that strengthens presentation confidence and structure.',
        capacity: 28,
        availableSlots: 8,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-008',
        title: 'Proofreading',
        category: 'Academic / Skills / Digital',
        date: '03 Jun 2026',
        sessionDate: '2026-06-03',
        venue: 'Language Lab',
        supervisorId: 'lec-002',
        description:
            'Language support activity focused on grammar, editing, and document review.',
        capacity: 26,
        availableSlots: 7,
        status: 'Draft',
      ),
      buildActivity(
        id: 'act-009',
        title: 'Fitness',
        category: 'Sports / Physical',
        date: '12 May 2026',
        sessionDate: '2026-05-12',
        venue: 'Sports Complex',
        supervisorId: 'lec-001',
        description:
            'Physical wellness activity designed to improve stamina, movement, and endurance.',
        capacity: 35,
        availableSlots: 11,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-010',
        title: 'Kayak',
        category: 'Sports / Physical',
        date: '14 May 2026',
        sessionDate: '2026-05-14',
        venue: 'Lake Training Centre',
        supervisorId: 'lec-003',
        description:
            'Outdoor skill activity focused on paddling technique, coordination, and safety.',
        capacity: 22,
        availableSlots: 0,
        status: 'Closed',
        isCompleted: true,
      ),
      buildActivity(
        id: 'act-011',
        title: 'Golf',
        category: 'Sports / Physical',
        date: '18 May 2026',
        sessionDate: '2026-05-18',
        venue: 'Golf Practice Range',
        supervisorId: 'lec-003',
        description:
            'Precision sports activity covering basic swing, posture, and etiquette.',
        capacity: 20,
        availableSlots: 5,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-012',
        title: 'Archery',
        category: 'Sports / Physical',
        date: '19 May 2026',
        sessionDate: '2026-05-19',
        venue: 'Archery Range',
        supervisorId: 'lec-003',
        description:
            'Technical outdoor activity focused on aim, control, and range discipline.',
        capacity: 24,
        availableSlots: 9,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-013',
        title: 'Futsal',
        category: 'Sports / Physical',
        date: '17 May 2026',
        sessionDate: '2026-05-17',
        venue: 'Indoor Court',
        supervisorId: 'lec-001',
        description:
            'Team-based sports activity that develops coordination, strategy, and fitness.',
        capacity: 24,
        availableSlots: 6,
        status: 'Active',
        isCompleted: true,
      ),
      buildActivity(
        id: 'act-014',
        title: 'Grooming and Etiquette',
        category: 'Soft Skills / Development',
        date: '04 Jun 2026',
        sessionDate: '2026-06-04',
        venue: 'Seminar Room B',
        supervisorId: 'lec-002',
        description:
            'Professional development activity focused on conduct, image, and workplace etiquette.',
        capacity: 30,
        availableSlots: 14,
        status: 'Draft',
      ),
      buildActivity(
        id: 'act-015',
        title: 'Event Management',
        category: 'Soft Skills / Development',
        date: '05 Jun 2026',
        sessionDate: '2026-06-05',
        venue: 'Convention Hall',
        supervisorId: 'lec-002',
        description:
            'Leadership and coordination activity covering planning, execution, and teamwork.',
        capacity: 30,
        availableSlots: 13,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-016',
        title: 'Psychological First Aid',
        category: 'Mental / Health',
        date: '06 Jun 2026',
        sessionDate: '2026-06-06',
        venue: 'Counselling Room',
        supervisorId: 'lec-001',
        description:
            'Support-focused activity on early response, empathy, and wellbeing awareness.',
        capacity: 25,
        availableSlots: 9,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-017',
        title: 'Mental Health',
        category: 'Mental / Health',
        date: '09 Jun 2026',
        sessionDate: '2026-06-09',
        venue: 'Student Support Centre',
        supervisorId: 'lec-001',
        description:
            'Awareness activity that builds resilience, reflection, and healthy coping practices.',
        capacity: 35,
        availableSlots: 16,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-018',
        title: 'Iqra',
        category: 'Religious / Spiritual',
        date: '10 Jun 2026',
        sessionDate: '2026-06-10',
        venue: 'Islamic Centre Room 1',
        supervisorId: 'lec-003',
        description:
            'Religious learning activity focused on guided recitation and foundational reading.',
        capacity: 25,
        availableSlots: 10,
        status: 'Draft',
      ),
      buildActivity(
        id: 'act-019',
        title: 'Tauhid',
        category: 'Religious / Spiritual',
        date: '11 Jun 2026',
        sessionDate: '2026-06-11',
        venue: 'Islamic Centre Room 2',
        supervisorId: 'lec-003',
        description:
            'Religious enrichment activity focused on faith understanding and reflective learning.',
        capacity: 25,
        availableSlots: 8,
        status: 'Active',
      ),
      buildActivity(
        id: 'act-020',
        title: 'Al-Fatihah',
        category: 'Religious / Spiritual',
        date: '12 Jun 2026',
        sessionDate: '2026-06-12',
        venue: 'Islamic Centre Room 3',
        supervisorId: 'lec-003',
        description:
            'Spiritual learning activity centred on recitation accuracy and meaning appreciation.',
        capacity: 25,
        availableSlots: 7,
        status: 'Active',
      ),
    ];
    final activityRegistrations = [
      {
        'id': 'actreg-001',
        'activityId': 'act-001',
        'studentId': 'stu-001',
        'registeredAt': createdAt,
        'status': 'completed',
        'attendanceStatus': 'present',
        'totalMarks': 90,
        'markStatus': 'passed',
        'evaluatedByLecturerId': 'lec-002',
        'verifiedByPusatAdabId': 'pad-001',
      },
      {
        'id': 'actreg-002',
        'activityId': 'act-013',
        'studentId': 'stu-001',
        'registeredAt': createdAt,
        'status': 'completed',
        'attendanceStatus': 'present',
        'totalMarks': 88,
        'markStatus': 'passed',
        'evaluatedByLecturerId': 'lec-001',
        'verifiedByPusatAdabId': 'pad-001',
      },
      {
        'id': 'actreg-003',
        'activityId': 'act-010',
        'studentId': 'stu-001',
        'registeredAt': createdAt,
        'status': 'completed',
        'attendanceStatus': 'present',
        'totalMarks': 84,
        'markStatus': 'passed',
        'evaluatedByLecturerId': 'lec-003',
        'verifiedByPusatAdabId': 'pad-001',
      },
      {
        'id': 'actreg-004',
        'activityId': 'act-002',
        'studentId': 'stu-001',
        'registeredAt': createdAt,
        'status': 'completed',
        'attendanceStatus': 'present',
        'totalMarks': 92,
        'markStatus': 'passed',
        'evaluatedByLecturerId': 'lec-001',
        'verifiedByPusatAdabId': 'pad-001',
      },
      {
        'id': 'actreg-005',
        'activityId': 'act-017',
        'studentId': 'stu-001',
        'registeredAt': createdAt,
        'status': 'completed',
        'attendanceStatus': 'present',
        'totalMarks': 86,
        'markStatus': 'passed',
        'evaluatedByLecturerId': 'lec-001',
        'verifiedByPusatAdabId': 'pad-001',
      },
    ];

    final creditClaims = [
      {
        'id': 'claim-001',
        'activityId': 'act-001',
        'activityIds': ['act-001', 'act-013', 'act-010', 'act-002'],
        'studentId': 'stu-001',
        'claimStatus': 'pending',
        'attendanceValidated': true,
        'allModulesPassed': true,
        'averageMark': 89,
        'totalHours': 32,
        'totalCats': 8,
        'submittedAt': createdAt,
        'reviewedBy': '',
        'reviewedAt': '',
        'remarks': 'Pending Pusat Adab review for the completed four-activity co-curriculum claim set with all marks recorded.',
      },
    ];

    final attendanceRecords = [
      {
        'id': 'att-001',
        'activityId': 'act-001',
        'attendanceCategory': 'module',
        'classCode': '353631',
        'createdAt': createdAt,
        'date': '2026-05-10',
        'detail': 'Checked in successfully',
        'lecturerId': 'lec-002',
        'lecturerName': 'Dr. Nabilah Hassan',
        'sessionId': 'session-1775497353631001',
        'sessionName': 'Session 1',
        'sourceOptionId': 'act-001',
        'status': 'Present',
        'studentId': 'stu-001',
        'studentIdentifier': '2023012345',
        'studentName': 'Ahmad Malik',
        'subjectName': 'Chess',
        'submissionMethod': 'Code',
        'time': '08:00 - 17:00',
      },
      {
        'id': 'att-002',
        'activityId': 'act-013',
        'attendanceCategory': 'module',
        'classCode': '353632',
        'createdAt': createdAt,
        'date': '2026-05-17',
        'detail': 'Checked in successfully',
        'lecturerId': 'lec-001',
        'lecturerName': 'Dr. Nur Hidayah',
        'sessionId': 'session-1775497353631002',
        'sessionName': 'Session 1',
        'sourceOptionId': 'act-013',
        'status': 'Present',
        'studentId': 'stu-001',
        'studentIdentifier': '2023012345',
        'studentName': 'Ahmad Malik',
        'subjectName': 'Futsal',
        'submissionMethod': 'Code',
        'time': '08:00 - 17:00',
      },
      {
        'id': 'att-003',
        'activityId': 'act-010',
        'attendanceCategory': 'module',
        'classCode': '353633',
        'createdAt': createdAt,
        'date': '2026-05-14',
        'detail': 'Checked in successfully',
        'lecturerId': 'lec-003',
        'lecturerName': 'Encik Danial Rizal',
        'sessionId': 'session-1775497353631003',
        'sessionName': 'Session 1',
        'sourceOptionId': 'act-010',
        'status': 'Present',
        'studentId': 'stu-001',
        'studentIdentifier': '2023012345',
        'studentName': 'Ahmad Malik',
        'subjectName': 'Kayak',
        'submissionMethod': 'Code',
        'time': '08:00 - 17:00',
      },
      {
        'id': 'att-004',
        'activityId': 'act-002',
        'attendanceCategory': 'module',
        'classCode': '353634',
        'createdAt': createdAt,
        'date': '2026-05-25',
        'detail': 'Checked in successfully',
        'lecturerId': 'lec-001',
        'lecturerName': 'Dr. Nur Hidayah',
        'sessionId': 'session-1775497353631004',
        'sessionName': 'Session 1',
        'sourceOptionId': 'act-002',
        'status': 'Present',
        'studentId': 'stu-001',
        'studentIdentifier': '2023012345',
        'studentName': 'Ahmad Malik',
        'subjectName': 'Creative Arts',
        'submissionMethod': 'Code',
        'time': '08:00 - 17:00',
      },
      {
        'id': 'att-005',
        'activityId': 'act-017',
        'attendanceCategory': 'module',
        'classCode': '353635',
        'createdAt': createdAt,
        'date': '2026-06-09',
        'detail': 'Checked in successfully',
        'lecturerId': 'lec-001',
        'lecturerName': 'Dr. Nur Hidayah',
        'sessionId': 'session-1775497353631005',
        'sessionName': 'Session 1',
        'sourceOptionId': 'act-017',
        'status': 'Present',
        'studentId': 'stu-001',
        'studentIdentifier': '2023012345',
        'studentName': 'Ahmad Malik',
        'subjectName': 'Mental Health',
        'submissionMethod': 'Code',
        'time': '08:00 - 17:00',
      },
    ];

    final attendanceSessions = [
      {
        'id': 'session-001',
        'attendanceCategory': 'module',
        'subjectName': 'Leadership Camp',
        'sessionName': 'Check In Session',
        'date': '2026-05-10',
        'time': '08:00 - 10:00',
        'classCode': '450001',
        'qrValue': 'QR-session-001',
        'lecturerId': 'lec-001',
        'lecturerName': 'Dr. Nur Hidayah',
        'latitude': 3.0738,
        'longitude': 101.5183,
        'allowedRadiusMeters': 100,
        'isActive': true,
        'sourceOptionId': 'act-001',
        'createdAt': createdAt,
      },
    ];

    return {
      'users': users,
      'tuition_fees': tuitionFees,
      'payment_transactions': paymentTransactions,
      'notifications': notifications,
      'subjects': subjects,
      'subject_offerings': subjectOfferings,
      'registration_periods': registrationPeriods,
      'subject_registrations': subjectRegistrations,
      'activities': activities,
      'activity_registrations': activityRegistrations,
      'credit_claims': creditClaims,
      'attendance_sessions': attendanceSessions,
      'attendance_records': attendanceRecords,
    };
  }
}






